"""Reproducibly generate the WS-1 synthetic sample, manifest, and truth set.

All content is obviously fake (synthetic tokens only) — no real PII (testing +
privacy rules). These are versioned test fixtures (hermetic); real controlled-sample
data lives under the git-ignored `poc/`. Run from the repo root:

    python tests/fixtures/build_ws1_sample.py

It writes tests/fixtures/ws1_sample/*, tests/fixtures/ws1_manifest.json, and
tests/fixtures/ws1_truth.json with content hashes that match the generated bytes.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

FIXTURES = Path("tests/fixtures")
SAMPLE_DIR = FIXTURES / "ws1_sample"
MANIFEST_PATH = FIXTURES / "ws1_manifest.json"
TRUTH_PATH = FIXTURES / "ws1_truth.json"

# A PNG signature + filler: not UTF-8 text, so the OCR gate must engage. Not a real
# image; sufficient for the skeleton.
_PNG_BYTES = bytes.fromhex("89504e470d0a1a0a") + b"\x00SYNTHETIC-SCAN-NO-TEXT-LAYER\x00"


def build() -> None:
    SAMPLE_DIR.mkdir(parents=True, exist_ok=True)
    manifest: list[dict[str, str]] = []
    truth: dict[str, dict[str, object]] = {}

    def add(
        source_id: str,
        filename: str,
        content_type: str,
        data: bytes,
        author: str,
        project: str,
    ) -> None:
        manifest.append(
            {
                "source_id": source_id,
                "content_type": content_type,
                "content_hash": hashlib.sha256(data).hexdigest(),
                "path": filename,
                "author": author,
                "datetime": "2026-01-15T09:30:00Z",
                "linked_executive": "exec-001",
                "linked_project": project,
            }
        )

    def write_text(filename: str, text: str) -> bytes:
        data = text.encode("utf-8")
        (SAMPLE_DIR / filename).write_bytes(data)
        return data

    def write_bytes(filename: str, data: bytes) -> bytes:
        (SAMPLE_DIR / filename).write_bytes(data)
        return data

    # note_001 — deterministic financial token, no hints -> FLAGGED (deterministic)
    data = write_text(
        "note_001.txt",
        "Prince Houston file note\n"
        "Client account reference ACCT-123456 confirmed during onboarding.\n"
        "Follow-up scheduled next week.\n",
    )
    add("note_001", "note_001.txt", "text/plain", data, "analyst-a", "proj-x")
    truth["note_001"] = {
        "flag_status": "flagged",
        "categories": ["financial"],
        "strongest_score_type": "deterministic_match",
    }

    # note_002 — benign -> NOT_FLAGGED
    data = write_text(
        "note_002.txt",
        "Prince Houston file note\n"
        "Team introductions completed. General availability discussed.\n"
        "No further actions at this time.\n",
    )
    add("note_002", "note_002.txt", "text/plain", data, "analyst-b", "proj-x")
    truth["note_002"] = {
        "flag_status": "not_flagged",
        "categories": [],
        "strongest_score_type": None,
    }

    # doc_born_001 — text layer + financial hint -> FLAGGED (model_score)
    data = write_text(
        "doc_born_001.pdf",
        "Executive compensation memo\n"
        "The proposed salary package is under review by the committee.\n",
    )
    add("doc_born_001", "doc_born_001.pdf", "application/pdf", data, "analyst-a", "proj-y")
    truth["doc_born_001"] = {
        "flag_status": "flagged",
        "categories": ["financial"],
        "strongest_score_type": "model_score",
    }

    # scan_001 — image, no text layer -> OCR gate; sidecar carries a gov-ID token
    data = write_bytes("scan_001.png", _PNG_BYTES)
    add("scan_001", "scan_001.png", "image/png", data, "analyst-c", "proj-y")
    write_text(
        "scan_001.png.ocr.txt",
        "Identity verification\n"
        "Passport on file. Reference GOVID-AB123456 recorded.\n",
    )
    truth["scan_001"] = {
        "flag_status": "flagged",
        "categories": ["government_id"],
        "strongest_score_type": "deterministic_match",
    }

    # unreadable_001 — unsupported type -> UNABLE_TO_PROCESS (unsupported_type)
    data = write_bytes("unreadable_001.dat", b"\x00\x01\x02BINARY-BLOB\xff\xfe")
    add(
        "unreadable_001",
        "unreadable_001.dat",
        "application/octet-stream",
        data,
        "analyst-c",
        "proj-z",
    )
    truth["unreadable_001"] = {
        "flag_status": "unable_to_process",
        "exception_code": "unsupported_type",
    }

    manifest.sort(key=lambda record: record["source_id"])
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    TRUTH_PATH.write_text(json.dumps(truth, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    build()
